import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Search, ArrowRight, Clock, Footprints, Sparkles, SlidersHorizontal, ArrowUpRight, Leaf } from 'lucide-react';
import { tours, destinations } from './campusData';

export function TourCard({ tour }) {
  return <article className="cp-tour-card"><Link to={`/tours/${tour.id}`} className="cp-card-image"><img src={tour.image} alt={tour.name} loading="lazy" /><span className="cp-image-tag"><Sparkles size={12} /> {tour.theme}</span></Link><div className="cp-card-body"><Link to={`/tours/${tour.id}`}><h3>{tour.short || tour.name}</h3></Link><p>{tour.description}</p><div className="cp-card-bottom"><span><Clock size={13} /> {tour.duration} min <Footprints size={13} /> Easy</span><Link to={`/tours/${tour.id}`}>Details <ArrowUpRight size={13} /></Link></div></div></article>;
}
export default function Explore() {
  const [search, setSearch] = useState('');
  const [term, setTerm] = useState('');
  const [theme, setTheme] = useState('All');
  const [duration, setDuration] = useState('All');
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [all, setAll] = useState(false);
  const filtered = tours.filter(t => (theme === 'All' || t.theme === theme) && (duration === 'All' || (duration === 'Short' ? t.duration < 30 : t.duration >= 30)) && `${t.name} ${t.short || ''} ${t.description}`.toLowerCase().includes(term.toLowerCase()));
  const filtering = term || theme !== 'All' || duration !== 'All';
  return <div className="cp-explore cp-container">
    <section className="cp-hero"><span className="cp-eyebrow"><Sparkles size={14} /> A NEW WAY TO EXPLORE</span><h1>Discover Your Campus Experience</h1><p>Explore our specialized autonomous tours tailored to your academic interests<br className="cp-desktop" /> and schedule.</p><form className="cp-search" onSubmit={e => { e.preventDefault(); setTerm(search); }}><label><Search size={18} /><input aria-label="Search tours" placeholder="Search tours, buildings, or topics..." value={search} onChange={e => setSearch(e.target.value)} /></label><select aria-label="Tour area" value={theme} onChange={e => setTheme(e.target.value)}><option value="All">All areas</option><option>Science</option><option>History</option><option>Nature</option></select><button className="cp-primary">Search</button></form></section>
    <button className="cp-filter-toggle cp-secondary" onClick={() => setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={16} /> Filters</button>
    <div className="cp-explore-grid"><aside className={`cp-filters ${filtersOpen ? 'open' : ''}`}><div className="cp-section-heading"><h3>Filters</h3><button onClick={() => { setTheme('All'); setDuration('All'); setSearch(''); setTerm(''); }}>Clear all</button></div><fieldset><legend>Duration</legend>{['All','Short','Medium'].map(d => <label key={d}><input type="radio" name="duration" checked={duration === d} onChange={() => setDuration(d)} />{d === 'All' ? 'Any duration' : d === 'Short' ? 'Short (<30 min)' : 'Medium (30–60 min)'}</label>)}</fieldset><fieldset><legend>Tour style</legend><p><Footprints size={14} /> Easy & relaxed</p><p><Leaf size={14} /> Electric campus tours</p></fieldset><fieldset><legend>Theme</legend><div className="cp-chips">{['All','Science','History','Nature'].map(t => <button className={theme === t ? 'selected' : ''} key={t} onClick={() => setTheme(t)}>{t}</button>)}</div></fieldset><div className="cp-filter-note"><Sparkles size={20} /><h4>Your campus. Your pace.</h4><p>Let your curiosity lead the way. Your AI guide takes care of the rest.</p><Link to="/guide">Meet your guide <ArrowRight size={13} /></Link></div></aside>
    <div className="cp-explore-content">
      {!filtering && <article className="cp-featured"><div className="cp-featured-image"><img src="/hero-campus.jpg" alt="Sunlit campus quad with autonomous tour robot" /><span className="cp-featured-tag"><Sparkles size={12} /> Tour of the Week</span><span className="cp-availability"><i /> Explore with an AI guide</span></div><div className="cp-featured-copy"><div className="cp-meta"><Clock size={13} /> 45 minutes <span>·</span> <Footprints size={13} /> Relaxed pace</div><h2>The Great Science Quad Adventure</h2><p>{tours[0].description}</p><Link className="cp-primary" to="/tours/campus">Book This Tour <ArrowRight size={15} /></Link></div></article>}
      <section className="cp-section"><div className="cp-section-heading"><h2>{filtering ? 'Search Results' : 'Popular Tours'}</h2><button onClick={() => setAll(!all)}>{all ? 'Show less' : 'See all'} <ArrowRight size={14} /></button></div><div className="cp-two-grid">{(filtering || all ? filtered : tours.slice(1,3)).map(t => <TourCard key={t.id} tour={t} />)}</div>{filtered.length === 0 && <div className="cp-empty"><Search size={28} /><h3>No tours found</h3><p>Try another search or clear your filters.</p></div>}</section>
      {!filtering && <><section className="cp-two-grid cp-section cp-mini-section"><div><h2>New Arrivals</h2><Link to="/tours/campus" className="cp-mini-card"><img src="/poi-student-union.jpg" alt="Student union" /><div><h3>Student Life & Hubs</h3><p>Immerse yourself in the vibrant student community.</p><span>Discover <ArrowRight size={12} /></span></div></Link></div><div><h2>Student Favorites</h2><Link to="/tours/garden" className="cp-mini-card"><img src="/tour-garden.jpg" alt="Campus garden" /><div><h3>Quiet Corners & Green Spaces</h3><p>A little escape between campus adventures.</p><span>Explore <ArrowRight size={12} /></span></div></Link></div></section>
      <section className="cp-feed cp-section"><div className="cp-section-heading"><h2>Campus Life Feed</h2><Link to="/guide">Ask your guide <ArrowUpRight size={14} /></Link></div><div className="cp-three-grid">{[['DISCOVER · TECHNOLOGY','Ideas that move us','Explore student innovations and the future of autonomous campus tours.','innovation'],['EXPLORE · CULTURE','A story around every corner','Get to know the architecture, shared spaces and stories of campus.','heritage'],['UNWIND · NATURE','Take the scenic route','Make room for fresh air and find your new favorite green space.','garden']].map(([tag,title,copy,id]) => <Link key={id} to={`/tours/${id}`}><span className="cp-eyebrow">{tag}</span><h3>{title}</h3><p>{copy}</p></Link>)}</div></section>
      <section className="cp-section"><div className="cp-section-heading"><h2>Top Destinations</h2><span className="cp-muted">Find your next stop</span></div><div className="cp-three-grid">{destinations.map(d => <Link to={`/tours/${d.tour}`} className="cp-destination" key={d.name}><img src={d.image} alt={d.name} loading="lazy" /><div><h3>{d.name}</h3><span>Discover this destination <ArrowUpRight size={13} /></span></div></Link>)}</div></section></>}
    </div></div>
  </div>;
}
