import { Link, useParams } from 'react-router-dom';
import { Bot, Clock, MapPin, Headphones, Accessibility, ShieldCheck, ArrowRight, Sparkles, Footprints } from 'lucide-react';
import { tours, destinations, useSlots } from './campusData';
import CampusMap from './CampusMap';

export default function TourDetail() {
  const { id } = useParams();
  const tour = tours.find(t => t.id === id);
  const { timeSlots, error, loading } = useSlots();
  if (!tour) return <div className="cp-container cp-empty"><h1>Tour not found</h1><Link to="/">Back to Explore</Link></div>;
  return <div className="cp-container cp-detail"><div className="cp-breadcrumb"><Link to="/">Explore</Link><span>/</span>{tour.name}</div><section className="cp-detail-hero"><img src={tour.image} alt={tour.name} /><div><span className="cp-glass-pill"><Sparkles size={13} /> Featured Tour <span>·</span><Clock size={13} /> {tour.duration} minutes</span><h1>{tour.name}</h1><p>{tour.description}</p></div></section>
    <div className="cp-detail-grid"><div><div className="cp-facts"><div><h3>Tour Highlights</h3><p><MapPin /> Historic landmarks</p><p><Bot /> Modern labs</p><p><Footprints /> Student life</p></div><div><h3>What's Included</h3><p><Sparkles /> AI voice guide</p><p><MapPin /> Digital map</p><p><Headphones /> On-the-go stories</p></div><div><h3>Know Before You Go</h3><p><Clock /> Arrive before your tour</p><p><Footprints /> Comfortable shoes</p><p><MapPin /> Check in at Main Hall</p></div></div>
    <section className="cp-section"><h2>Tour Route</h2><CampusMap /></section><section className="cp-section"><div className="cp-section-heading"><h2>Points of Interest</h2><Link to="/">View All <ArrowRight size={13} /></Link></div><div className="cp-poi-grid">{destinations.map((d,i) => <Link to={`/tours/${d.tour}`} className="cp-tour-card" key={d.name}><div className="cp-card-image"><img src={d.image} alt={d.name} /><span className="cp-image-tag"><MapPin size={11} /> Stop {i+1}</span></div><div className="cp-card-body"><h3>{d.name}</h3><p>{d.description}</p></div></Link>)}</div></section></div>
    <aside className="cp-booking-aside"><h3>Upcoming Availability</h3><p>Choose a departure time to get started.</p>{loading && <p>Checking tour times…</p>}{error && <p role="alert" className="cp-error">{error}</p>}{timeSlots.slice(0,4).map(t => <Link key={t} className="cp-slot-row" to={`/booking?tour=${tour.id}&time=${t}`}><Clock size={15} /><span>{t}<small>Campus departure</small></span><span className="cp-pill">Select</span></Link>)}<Link className="cp-primary cp-full" to={`/booking?tour=${tour.id}`}>Continue Booking <ArrowRight size={15} /></Link><p className="cp-fineprint">Explore campus at your own pace.</p></aside></div>
    <section className="cp-logistics" id="logistics"><h2>Technical & Logistics</h2><p>Everything you need to know about the tour experience and technology.</p><div className="cp-three-grid"><article><h3><MapPin size={18} /> Route Logistics</h3><p>Meet at the Entrance Gate.</p><p>Visit campus highlights along the route.</p><p>Check your booking for the selected route and departure time.</p></article><article><h3><Bot size={18} /> AMR Technology</h3><p>Explore with our autonomous mobile robots and follow your tour on the live campus map.</p><p>Ask the AI guide about the places along your journey.</p></article><article><h3><Accessibility size={18} /> Accessibility</h3><p>Choose a route that suits your mobility needs.</p><p>Contact campus staff before departure if you need boarding assistance.</p><p><ShieldCheck size={13} /> Follow the on-site safety instructions.</p></article></div></section>
  </div>;
}
